config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users 
  resources :documents
  root 'sessions#home'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get "/auth/google_oauth2/callback", to: 'sessions#google'

get "sessions/destroy"

controller :sessions do
delete 'logout' => :destroy
end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    # validates :username, presence: true, uniqueness: { case_sensitive: false },
  #                                          length: { in: 4..12 },
  #                                          format: { with: /A[a-z][a-z0-9]*z/, message: 'can only contain lowercase letters and numbers' }

    # validates :password, length: { in: 4..8 }
    # validates :password_confirmation, length: { in: 4..8 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
       @user = User.new
    end

    def create
        @user = User.new(user_params)
        
        if @user.save
           session[:user_id] = @user.id
           redirect_to user_path(@user)
        else
            render :new
        end
    end

    
    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end
    

    
    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/views/users/new.html.erb
user/new

<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
<%= f.label :username %>
<%= f.text_field :username, required:true %>
<br><br>
<%= f.label :email %>
<%= f.email_field :email %>
<br><br>
<%= f.label :password %>
<%= f.password_field :password %>
<br><br>
<%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
 user/show/show/html/erb
Wllcome <h1><%= @user.username %></h1>

<a href="<%= new_document_path %>">Next</a>