config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users 
  resources :documents
  root 'sessions#home'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get "/auth/google_oauth2/callback", to: 'sessions#google'

get "sessions/destroy"

controller :sessions do
delete 'logout' => :destroy
end
end

app/models/document.rb
class Document < ApplicationRecord
    belongs_to :user
    belongs_to :category

    scope :alpha, -> { order(:responsavel) }
    # scope :most_reviews, -> {left_joins(:reviews).group('jobs.id').order('count(reviews.job_id) desc')}
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @document = @user.documents.build
        else
        @document = Document.new
        end
        # binding.pry
         @document.build_category 
    end

    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
        # @documents = @user.documents
        @documentss = @user.documentss.alpha
     else
       @error = "That user doesn't exist" if params[:user_id]
       @documents = Document.alpha.includes(:category, :user)
     end
    end


 def create
   #@document = current_user.documents.build(document_params)
    @document = Document.new(document_params)
    #  @document.user = current_user
  # binding.pry
    if @document.save
      #  binding.pry
      flash[:success] = 'Your question has been posted!'
    redirect_to @documents
    else
     render :new
    end
end 


def edit
    @document = Document.find_by_id(params[:id])
    redirect_to documents_path if !@document || @document.user != current_user
    @document.build_category if !@job.category
  end

  def update
     @document = Document.find_by_id(id: params[:id])
     redirect_to documents_path if !@document || @document.user != current_user
    if @document.update(document_params)
      redirect_to document_path(@document)
    else
      render :edit
    end
  end



  def show 
        
    @document = Document.find_by_id(params[:id])
    redirect_to documents_path if !@document
end

private

def document_params
    params.require(:document).permit(:distribuidor, :responsavel, :data, :created_at, :visao, :missao, :codico, :snpj, :endereco, :email, :matriz, :filial, :filiall, :category_id, :category_attributes)
end



end

app/controllers/documents_controllers.rb
class DocumentsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @document = @user.documents.build
        else
        @document = Document.new
        end
        # @document.build_category 
    end

    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
        @documents = @user.documents.alpha
     else
       @error = "That user doesn't exist" if params[:user_id]
    #    @documents = Job.alpha.includes(:category, :user)
     end
 
    #  @jobs = @jobs.search(params[:q].downcase) if params[:q] && !params[:q].empty?
    #  @jobs = @jobs.filter(params[:job][:category_id]) if params[:job] && params[:job][:category_id] != ""
 
   end


   def create
    @document = current_user.documents.build(document_params)
    #binding.pry
    if @document.save
    redirect_to documents_path
    else
     render :new
    end
end 


def edit
    @document = Document.find_by_id(params[:id])
    redirect_to documents_path if !@document || @document.user != current_user
    # @document.build_category if !@job.category
  end

  def update
     @document = Document.find_by_id(id: params[:id])
     redirect_to documents_path if !@document || @document.user != current_user
    if @document.update(document_params)
      redirect_to document_path(@document)
    else
      render :edit
    end
  end



  def show 
        
    @document = Document.find_by_id(params[:id])
    redirect_to documents_path if !@document
end

private

def job_params
    params.require(:document).permit(:first_name, :last_name, :phone_number, :busness_email, :title, :description, :category_id, :category_attributes)
end



end

app/views/documents/index.html.erb
documents/index
<table class="styled-table">

<% @documents.each do |d| %>
    
    
<tbody>
<tr>
<td><h1><%= d.distribuidor %></h1> </td>
</tr>
<tr>
<td><h2><%= d.responsavel %></h2> </td>
</tr>
<tr>
<td><h2><%= d.created_at %></h2> </td>
</tr>

</tbody>

<table class="styled-table">
<tbody>
<tr>
<td><%= d.visao %></td>
</tr>
<tr>
<td><%= d.missao %></td>
</tr>
</tbody>
</table>

<table class="styled-table">
<tbody>
<tr>
<td><%= d.codico %></td>
</tr>
<tr>
<td><%= d.snpj %></td>
</tr>
<tr>
<td><%= d.endereco %></td>
</tr>
<tr>
<td><%= d.email %></td>
</tr>
<tr>
<td><%= d.matriz %>
</tr>
<tr>
<td><%= d.filial %></td>
</tr>
<tr>
<td><%= d.filiall %></td>
</tr>
</tbody>
</table>



<% end %>
</table>

app/views/documents/new.html.erb
<h1><%= current_user.username %></h1>

<table class="styled-table">

<tbody>
<h3> JBP 2021</h3>
<h1>Canal Distribuidores</h1>
<%= form_for(@document) do |f| %>

<tr>
<td>Company Name:</td>
<%= f.fields_for :category_attributes do |c|%>
<td><%= c.text_field :name%></td>
<% end %>
</tr>
  
<tr>
<td><%= f.label :distribuidor %></td>
<td><%= f.text_field :distribuidor, placeholder: "distribuidor" %><br><br></td>
</tr>
<tr>
<td><%= f.label :responsavel %></td>
<td><%= f.text_field :responsavel, placeholder: "responsavel"%><br><br></td>
</tr>
<tr>
<td><%= f.label :created_at %></td>
<td><%= f.datetime_local_field :created_at %><br><br></td>
</tr>
</tbody><br><br>
</table>

<table class="styled-table">
<tbody>
<tr>
<td><%= f.label :visao %>v
<td><%= f.text_field :visao, placeholder: "visao" %><br><br></td>
<tr>
<tr>
<td><%= f.label :missao %></td>
<td><%= f.text_field :missao, placeholder: "missao"%><br><br></td>
</tr>
</tbody>
</table>

<table class="styled-table">
<tbody>
<tr>
<td><%= f.label :codico %></td>
<td><%= f.text_field :codico, placeholder: "codico" %><br><br></td>
</tr>
<tr>
<td><%= f.label :snpj %>
<td><%= f.text_field :snpj, placeholder: "snpj"%><br><br></td>
</tr>
<tr>
<td><%= f.label :endereco %></td>
<td><%= f.text_field :endereco, placeholder: "endereco" %><br><br></td>
</tr>
<tr>
<td><%= f.label :email %></td>
<td><%= f.email_field :email, placeholder: "email"%><br><br></td>
</tr>
<tr>
<td><%= f.label :matriz %>
<td><%= f.text_field :matriz, placeholder: "matriz" %><br><br></td>
</tr>
<tr>
<td><%= f.label :filial %></td>
<td><%= f.text_field :filial, placeholder: "filial"%><br><br></td>
</tr>
<tr>
<td><%= f.label :filiall %></td>
<td><%= f.text_field :filiall, placeholder: "filiall"%><br><br></td>
</tr>
</tbody>
</table>

<%= f.submit "Submit" %>
<% end %>




    
</table>

app/views/documents/show.html.erb
<h1><%= @document.distribuidor %></h1>
<h2><%= @document.user.username %></h2>
<h2>By: <%=link_to @document.user.username, user_path(@document.user)%> </h2>


<h3>Category: <%= @document.category.try(:name)%></h3>
<% if @document.user == current_user %>
<h4><%= link_to "Edit Service", edit_document_path(@document)%></h4>
<% end %>

<div><%= @document.responsavel %></div>


# <p><%= link_to 'Add a new Review', new_job_review_path(@job) %></p>


# <% if !@job.reviews.empty? %>
# <p><%= link_to 'See all reviews', job_reviewss_path(@job)%></p>
# <h4>Most Recent Comments:</h4>
# <% @job.reviews.order(update_at: :desc).limit(4).each do |c| %>
#     <li>
# <strong><%= c.user.username %></strong> "<%= link_to c.description, job_review_path(@job, c) %>" at <%= c.updated_at.strftime("%I:%M %p on %m/%d/%Y") %>
# </li>
# <% end %>
# <% end %>